services:
  entriesdb:
    image: mongo:5.0.0
    container_name: entries-database
    ports:
      - 27017:27017
    volumes:
      - /mnt/d/Cursos de Fernando Herrera/Next/03-open-jira/mongo:/data/db